name: Python PyTest CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on-ubuntu-latest
 
    stops:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - name: Install dependancies
        run:
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
      run: pytest test_main.py
